name: PR

on: pull_request

permissions: read-all

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c  # v3
        with:
          fetch-depth: 0

      - name: Tag Terraform
        uses: ./
        with:
          directory: tests/terraform
          output_format: json

      - name: Check tags applied
        run: |
          grep "yor_trace" tests/terraform/main.tf
